Homework/Arrays
Jacob-Osho/myNewRepository pull request #10
Opened 2022-02-14 19:23 UTC by Jacob-Osho

2022-02-14 21:05 UTC, sergey-olefir requested changes

2022-02-14 21:05 UTC, sergey-olefir commented on firstApp/Arrays/Program.cs
> +                    case OrderBy.Ascending:
I'd add OrderBy as a param to sort method and made it optional

2022-02-14 21:05 UTC, sergey-olefir commented on firstApp/Arrays/Program.cs
> +            for (int i = 0; i < myNewArr.Length; i++)
foreach

2022-02-15 01:22 UTC, Jacob-Osho commented on firstApp/Arrays/Program.cs
> +                        if (i == array.Length - 1)
тупанул... вопросов нет

2022-02-15 01:40 UTC, Jacob-Osho commented on firstApp/Arrays/Program.cs
> +                    minIndex = Array.FindIndex(array, x => x == array2[i..].Min());
Solved Everything ! please check it !

2022-02-15 07:48 UTC, sergey-olefir requested changes

2022-02-15 07:48 UTC, sergey-olefir commented on firstApp/Arrays/Program.cs
> +                        //Array.FindIndex(array, x => x == array[i..].Min
Don't leave comments. It's a bad habit

2022-02-15 07:48 UTC, sergey-olefir commented on firstApp/Arrays/Program.cs
> +                            minIndex = j;
Try to follow a consistent code style. Spaces between equal sign

2022-02-15 07:48 UTC, sergey-olefir commented on firstApp/Arrays/Program.cs
> +                for (int b = 0; b < array.Length - 1; b++)
Better use j for nested loops. It's a standart

2022-02-15 07:48 UTC, sergey-olefir commented on firstApp/Arrays/Program.cs
> +
Spaces

2022-02-15 09:22 UTC, sergey-olefir requested changes

2022-02-15 09:22 UTC, sergey-olefir commented on firstApp/Arrays/Program.cs
> +            public static int[] SortArray(int[] myArr, SortAlgorithmType decision1, OrderBy decision2 = OrderBy.Ascending)
each algorithm should accept order direction. Let's move it.

2022-02-16 09:21 UTC, Jacob-Osho commented
решил все

2022-02-16 13:46 UTC, merged