homework-Strings
Jacob-Osho/myNewRepository pull request #11
Opened 2022-02-16 20:05 UTC by Jacob-Osho

2022-02-17 15:18 UTC, sergey-olefir requested changes

2022-02-17 15:18 UTC, sergey-olefir commented on firstApp/HomeworkStrings/Program.cs
> +        static char[] Duplicate(string firstString)
string must be returned

2022-02-17 15:18 UTC, sergey-olefir commented on firstApp/HomeworkStrings/Program.cs
> +        static char[] Duplicate(string firstString)
Can u please describe an yous algorithm flow?

2022-02-17 22:46 UTC, Jacob-Osho commented on firstApp/HomeworkStrings/Program.cs
> +        static char[] Duplicate(string firstString)
nah ,if we r talking about 38  row   i must notice that this is  Analyze method and it must return  number, so int fits perfect ,

2022-02-17 22:48 UTC, Jacob-Osho commented on firstApp/HomeworkStrings/Program.cs
> +            return firstString == secondString;
it's my own ,swear :)

2022-02-17 23:07 UTC, Jacob-Osho commented on firstApp/HomeworkStrings/Program.cs
> +        static char[] Duplicate(string firstString)
yep, np .
Step 1 - i sett all letters to lower case (because i am way to lazy to rape my ass with unnecessary moves) . 
Step 2- converting our string  to char array (1) and creating one more empty  char array (2)  with the length of  previous array.
Step3 - int counterOfDuplicateChars = 0;
            char temp;
            bool isDublicate = false;
Step 4 - i created 3 cycles  and here what i did :  1st is the parental cycle that consist of next two : second  checking - is our  char array (1) has duplicate chars if it's true  our tepm array (2) get it's value, counterOfDuplicateChars ++  and  isDublicate = true; third cycle i need to check  my temp array (2) for duplicates from my 1st array  if it's true my isDublicate  stay true otherwise it will be false
now i have  my temp array (2)  only with duplicated chars from  first array(1) and i know how many of this duplicated chars from first array(1) i have in my temp array(2) because of  counterOfDuplicateChars 
Step 5 i created new array(3) and it must have length of counterOfDuplicateChars 
and take all duplicated chars from temp array(2) to  it  ,then returned this new array(3) -"Peremoga"

2022-02-18 10:09 UTC, sergey-olefir approved these changes

2022-02-18 10:09 UTC, sergey-olefir commented on firstApp/HomeworkStrings/Program.cs
> +                        istrue =  false;
You can use early return. 
`return false;`

2022-02-18 10:09 UTC, sergey-olefir commented on firstApp/HomeworkStrings/Program.cs
> +                istrue= false;
`return false;`

2022-02-18 10:09 UTC, merged